version: "3.7"
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=datavise
    ports:
      - 3306:3306
    networks:
      - network-db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - network-db
networks:
  network-db:
