version: "3.7"
services:
  server:
    build:
      context: .
    env_file:
      - ./.env
    command: ${COMMAND_SERVER}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    networks:
      - backend
  neo4j:
    image: neo4j
    ports:
      - 7474:7474 # Web interface
      - 7687:7687 # Bolt Interface
    env_file:
      - ./.env
    environment:
      - NEO4J_AUTH
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474
    volumes:
      - ./database/neo4j/plugins:/plugins
      - ./database/neo4j/neo4j:/data
      - ./database/neo4j/import:/import
    networks:
      - backend

networks:
  backend:
    name: backend
