version: "3.7"
services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474 # Web interface
      - 7687:7687 # Bolt Interface
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/password #username/password pair
      - NEO4J_dbms_connector_http_advertised__address=0.0.0.0:7474
    volumes:
      - ./neo4j-volumes/plugins:/plugins
      - ./neo4j-volumes/neo4j:/data
      - ./neo4j-volumes/import:/import # a simple access to import a lot of data
